---
changelogPolicy: simple
github:
  owner: getsentry
  repo: sentry-fullstory
minVersion: "0.24.4"
preReleaseCommand: bash scripts/craft-pre-release.sh
targets:
  - name: npm
  - name: github
    tagPrefix: v
