branches:
  only:
    - master
    - /^release\/.+$/

language: node_js

cache:
  yarn: true
  directories:
    - node_modules

matrix:
  include:
    - name: 'deploy'
      node_js: '10'
      script:
        - yarn
        - yarn build
        - yarn pack
      after_success:
        - yarn global add @zeus-ci/cli
        - zeus upload -t "application/tar+npm" *.tgz

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/c367b41c-25bb-11ea-bc57-fe9b72ea5eaf/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
