name: Deploy Prep

on:
  push:
    branches:
      - $default-branch
      - /^release\/.+$/
  pull_request:

jobs:
  deploy_prep:
    name: Deploy Prep
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install and cache node modules
      - uses: actions/setup-node@v2
      - with:
          node-version: '12'
          cache: 'yarn'
      - run: yarn install

      - name: Build distributables
      - run: yarn build

      - name: Generate tarball artifact
      - run: yarn pack

  release_prep:
    name: Release Prep
    runs-on: ubuntu-latest
    needs: deploy_prep

    steps:
      - uses: actions/checkout@v2
      - name: Upload artifacts for release
      - uses: actions/upload-artifact@v2
        with:
          path: *.tgz
